github:
  api_version: "v3"
  max_file_size: 1048576 #1MB
  analysis_options:
    complexity_threshold: 10
    pylint_enabled: true

logging:
  level: "INFO"
  file_path: "logs/"

report:
  output_formats:
    - markdown
    - html

  include_sections:
    - complexity
    - halstead_metrics
    - pylint_issues
